[package]
name = "syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { workspace = true }
anyhow = { workspace = true }
tokio = { version = "1.38.0", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "time",
] }
