[package]
name = "algorithm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
num = { workspace = true }
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
